version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:17
    container_name: bibliotheque_db
    environment:
      POSTGRES_DB: bibliotheque
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bibliotheque"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: